spring:
  datasource:
    url: jdbc:h2:C:\Users\evajj\IdeaProjects\MySpringBoot2Dbase\testdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  h2:
    console.enabled: true
server:
  port: 8084

